### ISSUE TITLE
有没有出一个Vue3版本的想法？

### ISSUE THREAD

**Issue by renmengkai** [lencx/WA#1]
如题，个人更喜欢使用Vue，所以问下楼主有没有搞一个Vue3版本的想法

**Comment by lencx** [comment]
Vue 我不太熟悉，前端使用哪个技术栈其实没有太大区别，都是画 UI 而已。

**Comment by renmengkai** [comment]
同意你的说法，只是如果把该项目作为脚手架会涉及到前端技术的选型，所以问下
