### ISSUE TITLE
以更好的处理方式处理setting.json解析错误

### ISSUE THREAD

**Issue by yixinBC** [lencx/WA#3]
在写setting.json里的配置的时候不小心写错了，结果返回后主页面直接无法渲染，只能手动在别的文本编辑器里打开配置文件进行更改。
奈何本人技术水平有限，无法提pr，望大佬能在后续版本中修复😘

**Comment by lencx** [comment]
谢谢建议。目前返回首页也可以重新点击编辑按钮，这个还是 demo 版本，后续会加上错误提示，引导帮助等等，可以保持关注。
