### ISSUE TITLE
考虑使用npm替代yarn作为默认的包管理器。

### ISSUE THREAD

**Issue by ljybill** [lencx/WA#5]
https://github.com/lencx/WA/blob/67aed877d025f75a054a3e9f0f8009f3ba856b83/src-tauri/tauri.conf.json#L3

主要是因为我电脑没安装yarn启动项目时报错了，把这里改成npm就可以了。

**Comment by lencx** [comment]
谢谢建议，我修改一下，这个是初始化选择包管理默认的。
